Tatvasoft_Project/Models/Book_now_Table.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Tatvasoft_Project.Models
{
    public class Book_now_Table
    {
        public int ID { get; set; }
        public string Zipcode { get; set; }
        public DateTime Booking_date { get; set; }
        public string Booking_time { get; set; }
        public string Booking_duration { get; set; }
        public int Cabinate { get; set; }
        public int Fridge { get; set; }
        public int Oven { get; set; }
        public int Laundry { get; set; }
        public int Windows { get; set; }
        public string Suggestion { get; set; }
        public bool Pets { get; set; }
        public string Street { get; set; }
        public string House_number { get; set; }
        public string PLZ { get; set; }
        public string Location { get; set; }
        public string Phone { get; set; }
        public int to_check { get; set; }
        public float Total_cost { get; set; }
        public float Discounted_cost { get; set; }
        public int? Status { get; set; }
        public string SP_Name { get; set; }
        public float SP_Ratings { get; set; }
        public int? SP_ID { get; set; }
        public int Is_Date_Smaller { get; set; }
        public int Is_Blocked { get; set; }
        public string Customer_Name { get; set; }
        public int Is_Fav { get; set; }
        public string Date_String { get; set; }
    }
}

Tatvasoft_Project/Controllers/HelperlandController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Threading.Tasks;
using Tatvasoft_Project.Data;
using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore;
using System.Data.SqlTypes;
using Microsoft.AspNetCore.Session;
using Microsoft.AspNetCore.Http;
using System.Dynamic;

namespace Tatvasoft_Project.Controllers
{
    public class HelperlandController : Controller
    {
        private HelperlandContext _helperlandcontext;
        //private Models.Session ssn;
        //private object userManager;


        public object Session { get; set; }
        
        

        public IActionResult Index()
        {
            ViewBag.user = HttpContext.Session.GetString("user");
            ViewBag.sugg = HttpContext.Session.GetString("Booking_instruction");
            return View("~/Views/Home/Index.cshtml");

        }

        public ViewResult Prices()
        {
            ViewBag.user = HttpContext.Session.GetString("user");

            return View();
        }

        public ViewResult Contact()
        {
            ViewBag.user = HttpContext.Session.GetString("user");
            return View();
        }

        public ViewResult FAQ()
        {
            ViewBag.user = HttpContext.Session.GetString("user");
            return View();
        }

        public ViewResult About()
        {
            ViewBag.user = HttpContext.Session.GetString("user");
            return View();
        }
        public ViewResult Become_helper()
        {
            ViewBag.user = HttpContext.Session.GetString("user");
            return View();
        }
        public ViewResult New_user()
        {
            return View();
        }
        public IActionResult Register(Models.User model)
        {
            Models.User obj = new Models.User();
            obj.FirstName = model.FirstName;
            obj.LastName = model.LastName;
            obj.Email = model.Email;
            obj.Mobile = model.Mobile;
            obj.ZipCode = model.ZipCode;
            obj.UserTypeId = 1;
            obj.IsRegisteredUser = true;
            obj.WorksWithPets = model.WorksWithPets;
            obj.DateOfBirth = model.DateOfBirth;
            obj.CreatedDate = DateTime.Today;
            obj.ModifiedDate = DateTime.Today;
            obj.ModifiedBy = 1;
            obj.IsApproved = true;
            obj.IsActive = true;
            obj.IsDeleted = true;
            obj.IsOnline = true;
            var key = Guid.NewGuid();
            obj.ResetKey = "h" + key;
            _helperlandcontext = new HelperlandContext();
            obj.Password = BCrypt.Net.BCrypt.HashPassword(model.Password);
            var p = _helperlandcontext.Users.Where(x => x.Email == model.Email).ToList();
            if (p.Count >= 1)
            {
                ViewBag.err = "Email ID Already Exist, Please use different Email ID";
                return View("~/Views/Helperland/New_user.cshtml");
            }
            var user = model.FirstName;
            HttpContext.Session.SetString("user", user);
            ViewBag.user = HttpContext.Session.GetString("user");
            _helperlandcontext.Users.Add(obj);
            _helperlandcontext.SaveChanges();
            return View();
        }

        public IActionResult Register_sp(Models.User model)
        {
            Models.User obj = new Models.User();
            obj.FirstName = model.FirstName;
            obj.LastName = model.LastName;
            obj.Email = model.Email;
            obj.Mobile = model.Mobile;
            obj.ZipCode = model.ZipCode;
            obj.UserTypeId = 2;
            obj.IsRegisteredUser = true;
            obj.WorksWithPets = false;
            obj.DateOfBirth = model.DateOfBirth;
            obj.CreatedDate = DateTime.Today;
            obj.ModifiedDate = DateTime.Today;
            obj.ModifiedBy = 2;
            obj.IsApproved = true;
            obj.IsActive = true;
            obj.IsDeleted = true;
            obj.IsOnline = true;
            obj.IsApproved = false;
            _helperlandcontext = new HelperlandContext();
            obj.Password = BCrypt.Net.BCrypt.HashPassword(model.Password);
            obj.ResetKey = (Guid.NewGuid()).ToString();
            var p = _helperlandcontext.Users.Where(x => x.Email == model.Email).ToList();
            if (p.Count >= 1)
            {
                ViewBag.err = "Email ID Already Exist, Please use different Email ID";
                return View("~/Views/Helperland/Become_helper.cshtml");
            }
            var user = model.FirstName;
            HttpContext.Session.SetString("user", user);
            ViewBag.user = HttpContext.Session.GetString("user");
            _helperlandcontext.Users.Add(obj);
            _helperlandcontext.SaveChanges();
            return View();
        }

        public IActionResult Login(Models.User model)
        {
            _helperlandcontext = new HelperlandContext();
            string email = model.Email;

            if(email == "Admin@gmail.com" && model.Password == "Admin")
            {
                return Redirect("/Admin/Customer_Page");
            }

            var p = _helperlandcontext.Users.Where(x => x.Email == email).ToList();
            
            if (p.Count == 1)
            {
                var user = p.FirstOrDefault().FirstName;
                HttpContext.Session.SetString("user", user);

                bool is_pass_valid = BCrypt.Net.BCrypt.Verify(model.Password, p.FirstOrDefault().Password);
                if(is_pass_valid)
                {
                    if (p.FirstOrDefault().UserTypeId == 1 && p.FirstOrDefault().IsActive == true)
                    {
                        //var user = p.FirstOrDefault().FirstName;
                        //HttpContext.Session.SetString("user", user);
                        var username = HttpContext.Session.GetString("user");
                        _helperlandcontext = new HelperlandContext();
                        var userid = (_helperlandcontext.Users.Where(x => x.FirstName == username).ToList()).FirstOrDefault().UserId;
                        var model_to_pass = _helperlandcontext.ServiceRequests.Where(x => x.UserId == userid && ((x.Status == null) || x.Status == 3)).ToList();
                        List<Models.Book_now_Table> item = new List<Models.Book_now_Table>();
                        foreach (Models.ServiceRequest temp in model_to_pass)
                        {
                            if (temp.ServiceRequestId >= 4)
                            {
                                var duration = (temp.ServiceHours).ToString();
                                if (duration.Length <= 2)
                                {
                                    duration += ":00";
                                }
                                else duration = Math.Round(temp.ServiceHours, 2).ToString() + '0';
                                var end_dur = Math.Round(double.Parse((temp.ServiceHours + temp.ExtraHours).ToString()), 2).ToString();
                                if (end_dur.ToString().Length <= 2)
                                {
                                    duration = duration + "-" + end_dur.ToString() + ":00";
                                }
                                else duration = (duration + "-" + end_dur.ToString() + '0').Replace('.', ':');

                                var spid = _helperlandcontext.ServiceRequests.Where(x => x.ServiceRequestId == temp.ServiceRequestId && temp.ServiceProviderId != null).ToList();
                                int? spid3 = 0;
                                var name = "";

                                var rating = 0;
                                if (spid.Count > 0)
                                {
                                    spid3 = (spid.FirstOrDefault().ServiceProviderId);
                                    var fname = _helperlandcontext.Users.Where(x => x.UserId == spid3).ToList().FirstOrDefault().FirstName;
                                    var lname = _helperlandcontext.Users.Where(x => x.UserId == spid3).ToList().FirstOrDefault().LastName;
                                    name = fname + " " + lname;


                                }

                                item.Add(new Models.Book_now_Table
                                {
                                    SP_ID = spid3,
                                    SP_Name = name,
                                    ID = temp.ServiceRequestId,
                                    Booking_date = (temp.ServiceStartDate).Date,
                                    Booking_time = (temp.ExtraHours).ToString(),
                                    Discounted_cost = float.Parse((temp.SubTotal).ToString()),
                                    Booking_duration = duration,
                                    Suggestion = temp.Comments,

                                });
                            }
                        }
                        int i = 0;
                        foreach (Models.ServiceRequest temp2 in model_to_pass)
                        {
                            if (temp2.ServiceRequestId >= 4)
                            {


                                var address_obj = _helperlandcontext.ServiceRequestAddresses.Where(x => x.ServiceRequestId == temp2.ServiceRequestId).ToList();

                                //int id = temp2.ServiceId;
                                item[i].Street = address_obj[0].AddressLine1;
                                item[i].House_number = address_obj.FirstOrDefault().AddressLine2;
                                item[i].Zipcode = address_obj.FirstOrDefault().PostalCode;
                                item[i].Location = address_obj.FirstOrDefault().City;
                                item[i].Phone = address_obj.FirstOrDefault().Mobile;

Tatvasoft_Project/Views/Helperland/Forgot_password.cshtml
<html>
<head>

</head>
<body>
    <h2 style="color:green;width:100%;text-align:center;">Email is sent to given Email id, You can Create your new password using link given in email. Thanks!</h2>
</body>
</html>

Tatvasoft_Project/Views/Helperland/Login.cshtml
<html>
<head>

</head>
<body>
    <h3>@ViewBag.err</h3>
    <h1>Login Success</h1>
</body>
</html>

Tatvasoft_Project/Views/Helperland/New_user.cshtml
@model User

<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <title>Hello, world!</title>
    <link rel="stylesheet" type="text/css" href="../css/style2.css">
</head>
<body>
    <h1 style="text-align: center;margin-top: 15px;">Create an account</h1>
    <div class="contact_arw">
        <div class="dec_lines">_______</div>&nbsp;
        <img class="dec_img" src="~/images/contact_arr.png">&nbsp;
        <div class="dec_lines">_______</div>
    </div>

    <form onsubmit="return validation()" asp-controller="Helperland" asp-action="Register" method="post" class="container-fluid" style="margin-top: 30px;">
        <div class="form-row">
            <div class="form-group col-md-6">
                <input required id="firstname" type="text" class="form-control" asp-for="FirstName" placeholder="First Name">
            </div>
            <div class="form-group col-md-6">
                <input required type="text" class="form-control" id="lastname" asp-for="LastName" placeholder="Last Name">
            </div>
        </div>
        <div class="form-row">

            <div class="form-group col-md-6">
                <input required type="Email" class="form-control" id="email" asp-for="Email" placeholder="Email address">
            </div>
            <div class="form-group col-md-1">
                <input type="text" readonly class="form-control" id="inputEmail4" placeholder="+49">
            </div>
            <div class="form-group col-md-5">
                <input required type="text" class="form-control" id="mobile" asp-for="Mobile" placeholder="Mobile number">
            </div>
        </div>

        <div class="form-row">
            <div class="form-group col-md-6">
                <input required type="password" class="form-control" id="password" asp-for="Password" placeholder="Password">
            </div>
            <div class="form-group col-md-6">
                <input required type="password" class="form-control" id="confirmpassword" placeholder="Confirm Password">
            </div>
        </div>

        <div class="form-row">
            <div class="form-group col-md-6">
                <input required type="text" class="form-control" id="zipcode" asp-for="ZipCode" placeholder="Zipcode">
            </div>
            <div class="form-group col-md-6">
                <input required type="date" class="form-control" id="dob" asp-for="DateOfBirth" placeholder="Date of Birth">
            </div>
        </div>

        <input type="checkbox" required name="cb"> I have read the <a href="#" data-toggle="modal" data-target="#exampleModalLong">Privacy Policy</a>
        <br><input type="checkbox" name="pets" asp-for="WorksWithPets"> I have pets at home

        <div class="text-center">
            <button type="submit" class="btn btn-primary btn_register_demo" style=" width: 130px; border-radius: 20px; margin-top: 7px; ">Register</button>
        </div>
    </form>

    <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Login to your Account</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">

                    <form style="margin-bottom: 15px;">
                        <div class="form-group">
                            <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Email">
                        </div>
                        <div class="form-group">
                            <input type="password" class="form-control" id="exampleInputPassword1" placeholder="Password">
                        </div>
                        <div class="form-group form-check">
                            <input type="checkbox" class="form-check-input" id="exampleCheck1">
                            <label class="form-check-label" for="exampleCheck1">Remember Me</label>
                        </div>
                        <button style="width: 90%;margin-top:10px; center;border-radius: 20px;background-color: #3398FF;margin-left: 5%;" type="submit" class="btn">
                            <a href="#" style="color: white;font-size: 18px;">Login</a>
                        </button>
                    </form>

                    <a href="#" id="id_FP" class="F_p" onclick="f1()" data-toggle="modal" data-target="#forgotpassword">Forgot Password?</a>
                    <div class="c_a">Don't have an Account? <a href="/Helperland/New_user">Create an Account</a></div>

                </div>

            </div>
        </div>
    </div>

    <div class="modal fade" id="forgotpassword" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true" style="background-color: gray;">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Forgot Password</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">

                    <form style="margin-bottom: 15px;">
                        <div class="form-group">
                            <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Email Address">
                        </div>

                        <button style="width: 90%;text-align: center;border-radius: 20px;background-color: #3398FF;margin-left: 5%;" type="submit" class="btn">
                            <a href="#" style="color: white;font-size: 18px;">Send</a>
                        </button>
                    </form>f

                    <a href="#" class="LN" data-toggle="modal" data-target="#forgotpassword">Login now</a>

                </div>
                
            </div>
        </div>
    </div>


    <div class="container-fluid temp_lst_lgin_now" style=" text-align: center; margin-top: 10px; ">Already registered? 
    <a href="#" data-toggle="modal" data-target="#exampleModal">Login now</a></div>


    <!-- Button trigger modal -->
    <!-- Modal -->
    <div class="modal fade" id="exampleModalLong" tabindex="-1" role="dialog" aria-labelledby="exampleModalLongTitle" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLongTitle">Modal title</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    ...
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>

    @if(ViewBag.err != null)
            {
               <script>
                   alert("@ViewBag.err");
               </script>
            }

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

    <script>
        function validation()
        {
            var firstname = document.getElementById('firstname').value;
            var lastname = document.getElementById('lastname').value;
            var email = document.getElementById('email').value;
            var mobile = document.getElementById('mobile').value;
            var password = document.getElementById('password').value;
            var confirmpassword = document.getElementById('confirmpassword').value;
            var zipcode = document.getElementById('zipcode').value;
            var dob = document.getElementById('dob').value;

            if(firstname.length < 5 || lastname.length < 5)
            {
                alert("Minimum Length of first name and last name must be 5");
                return false;
            }
            if(mobile.length != 10)
            {
                alert("Length of mobile number must be 10");
                return false;
            }
            if(password.length < 5 || confirmpassword.length < 5)
            {
                alert("Minimum length of password and confirm password must be 5");
                return false;
            }
            if(zipcode.length != 6)
            {
                alert("length of zipcode must be 6");
                return false;
            }
            if(password != confirmpassword)
            {
                alert("Password and Confirm password must be same");
                return false;
            }
            if(isNaN(mobile))
            {
                alert("mobile number must only contain digits");
                return false;
            }
            if(isNaN(zipcode))
            {
                alert("zipcode must only contain digits");
                return false;
            }
            return true;
        }
    </script>

</body>
</html>

Tatvasoft_Project/Views/Helperland/Reset_pass.cshtml
<html>
<head>

</head>
<body>
    Hello, password reset done.
</body>
</html>

Tatvasoft_Project/Views/Helperland/Reset_password.cshtml
@model User
    <!doctype html>
    <html lang="en">
    <head>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <!-- Bootstrap CSS -->
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

        <title>Hello, world!</title>
    </head>
    <body>

        <div class="container-fluid" style="margin-top:25px;">
            <form onsubmit="return validate()" asp-action="Reset_pass" asp-controller="Helperland" method="post">
                <div class="form-group">
                    <label for="exampleInputEmail1">New Password</label>
                    <input style="border:1px solid black;" asp-for="Password"  type="password" class="form-control" id="password" aria-describedby="emailHelp" placeholder="New Password">
                </div>
                <div class="form-group">
                    <label for="exampleInputPassword2">Confirm Password</label>
                    <input style="border:1px solid black;" type="password" class="form-control" id="confirmpassword" placeholder="Confirm Password">
                </div>

                <input type="text" asp-for="UserId" value=@ViewBag.key hidden />

                <button type="submit" class="btn btn-primary">Reset Password</button>
            </form>


        </div>
        <!-- Optional JavaScript -->
        <!-- jQuery first, then Popper.js, then Bootstrap JS -->
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    
        <script>
            function validate()
            {
                var password = document.getElementById('password').value;
                var confirmpassword = document.getElementById('confirmpassword').value;

                if(password != confirmpassword)
                {
                    alert("password and confirm password must match");
                    return false;
                }
                if(password.length < 5 || confirmpassword.length < 5)
                {
                    alert("Minimum Length of password and confirm password must be 5");
                    return false;
                }
                return true;
            }

        </script>
    
    </body>
</html>