Tatvasoft_Project/Models/Rating.cs
using System;
using System.Collections.Generic;

#nullable disable

namespace Tatvasoft_Project.Models
{
    public partial class Rating
    {
        public int RatingId { get; set; }
        public int ServiceRequestId { get; set; }
        public int RatingFrom { get; set; }
        public int RatingTo { get; set; }
        public decimal Ratings { get; set; }
        public string Comments { get; set; }
        public DateTime RatingDate { get; set; }
        public bool? IsApproved { get; set; }
        public bool VisibleOnHomeScreen { get; set; }
        public decimal OnTimeArrival { get; set; }
        public decimal Friendly { get; set; }
        public decimal QualityOfService { get; set; }

        public virtual User RatingFromNavigation { get; set; }
        public virtual User RatingToNavigation { get; set; }
        public virtual ServiceRequest ServiceRequest { get; set; }
    }
}

Tatvasoft_Project/Controllers/Service_ProviderController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Threading.Tasks;
using Tatvasoft_Project.Data;
using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore;
using System.Data.SqlTypes;
using Microsoft.AspNetCore.Session;
using Microsoft.AspNetCore.Http;
using System.Dynamic;

namespace Tatvasoft_Project.Controllers
{
    public class Service_ProviderController : Controller
    {
        private HelperlandContext _helperlandcontext;

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult SP_Dashboard()
        {
            _helperlandcontext = new HelperlandContext();
            var username = HttpContext.Session.GetString("user");
            _helperlandcontext = new HelperlandContext();
            var userid = (_helperlandcontext.Users.Where(x => x.FirstName == username).ToList()).FirstOrDefault().ZipCode;

            var targetuserid = (_helperlandcontext.Users.Where(x => x.FirstName == username).ToList()).FirstOrDefault().UserId;
            var model_to_pass = _helperlandcontext.ServiceRequests.Where(x => x.ZipCode == userid && x.Status == null).ToList();
            List<Models.Book_now_Table> item = new List<Models.Book_now_Table>();
            foreach (Models.ServiceRequest temp in model_to_pass)
            {

                if (temp.ServiceRequestId >= 4)
                {
                    var spid = _helperlandcontext.Users.Where(x => x.UserId == temp.UserId).ToList();

                    var blocked_count = _helperlandcontext.FavoriteAndBlockeds.Where(x => x.UserId == spid.FirstOrDefault().UserId
                    && x.TargetUserId == targetuserid && x.IsBlocked == true).ToList();

                    if (blocked_count.Count == 0)
                    {

                        var duration = (temp.ServiceHours).ToString();
                        if (duration.Length <= 2)
                        {
                            duration += ":00";
                        }
                        else duration = Math.Round(temp.ServiceHours, 2).ToString() + '0';
                        var end_dur = Math.Round(double.Parse((temp.ServiceHours + temp.ExtraHours).ToString()), 2).ToString();
                        if (end_dur.ToString().Length <= 2)
                        {
                            duration = duration + "-" + end_dur.ToString() + ":00";
                        }
                        else duration = (duration + "-" + end_dur.ToString() + '0').Replace('.', ':');

                        int? spid3 = 0;
                        var name = "";



                        //var rating = 0;
                        if (spid.Count > 0)
                        {
                            spid3 = (spid.FirstOrDefault().UserId);
                            var fname = spid.FirstOrDefault().FirstName;
                            var lname = spid.FirstOrDefault().LastName;
                            name = fname + " " + lname;


                        }
                        item.Add(new Models.Book_now_Table
                        {
                            SP_ID = spid3,
                            SP_Name = name,
                            ID = temp.ServiceRequestId,
                            Booking_date = (temp.ServiceStartDate).Date,
                            Booking_time = (temp.ExtraHours).ToString(),
                            Discounted_cost = float.Parse((temp.SubTotal).ToString()),
                            Booking_duration = duration,
                            Suggestion = temp.Comments,
                            Status = temp.Status
                        });
                    }
                }
            }
            int i = 0;
            foreach (Models.ServiceRequest temp2 in model_to_pass)
            {
                if (temp2.ServiceRequestId >= 4)
                {
                    var spid = _helperlandcontext.Users.Where(x => x.UserId == temp2.UserId).ToList();

                    var blocked_count = _helperlandcontext.FavoriteAndBlockeds.Where(x => x.UserId == spid.FirstOrDefault().UserId
                    && x.TargetUserId == targetuserid && x.IsBlocked == true).ToList();

                    if (blocked_count.Count == 0)
                    {



                        var address_obj = _helperlandcontext.ServiceRequestAddresses.Where(x => x.ServiceRequestId == temp2.ServiceRequestId).ToList();

                        //int id = temp2.ServiceId;
                        item[i].Street = address_obj[0].AddressLine1;
                        item[i].House_number = address_obj.FirstOrDefault().AddressLine2;
                        item[i].Zipcode = address_obj.FirstOrDefault().PostalCode;
                        item[i].Location = address_obj.FirstOrDefault().City;
                        item[i].Phone = address_obj.FirstOrDefault().Mobile;
                        i++;
                    }
                }
            }

            ViewBag.user = HttpContext.Session.GetString("user");
            ViewBag.data = item;
            var unme = HttpContext.Session.GetString("user");
            ViewBag.uid = _helperlandcontext.Users.Where(x => x.FirstName == unme).ToList().FirstOrDefault().UserId;

            return View();
        }

        public IActionResult Fetch_ES(int sid, int spid)
        {
            _helperlandcontext = new HelperlandContext();
           
            var obj = _helperlandcontext.ServiceRequests.Where(x => x.ServiceRequestId == sid).ToList().FirstOrDefault();
            obj.PaymentDue = true;

            var all_services = _helperlandcontext.ServiceRequests.Where(x => x.Status == 3 && x.ServiceProviderId == spid).ToList();
            var services = _helperlandcontext.ServiceRequests.Where(x => x.ServiceRequestId == sid).ToList().FirstOrDefault();
            var service_date = services.ServiceStartDate;
            var service_start_time = services.ServiceHours;
            var service_end_time = services.ExtraHours + services.ServiceHours;

            foreach(var tmpp in all_services)
            {
                if(tmpp.ServiceStartDate == service_date)
                {
                    var start_time = tmpp.ServiceHours;
                    var end_time = tmpp.ExtraHours + tmpp.ServiceHours;
                    if(service_start_time >= (start_time-1) && service_start_time <= (end_time + 1))
                    {
                        obj.PaymentDue = false;
                    }
                    else if (service_start_time >= (start_time - 1) && service_end_time <= (end_time + 1))
                    {
                        obj.PaymentDue = false;
                    }
                    else if(service_start_time <= (start_time - 1) && service_end_time >= (start_time - 1))
                    {
                        obj.PaymentDue = false;
                    }
                    else if (service_start_time <= (start_time - 1) && service_end_time >= (end_time + 1))
                    {
                        obj.PaymentDue = false;
                    }
                    
                   
                    
                }
            }

            //var obj = _helperlandcontext.ServiceRequests.Where(x => x.ServiceRequestId == sid).ToList().FirstOrDefault();
            


            if (obj.PaymentDue == true)
            {
                obj.ServiceProviderId = spid;
                obj.Status = 3;

                _helperlandcontext.Entry(obj).State = EntityState.Modified;
                _helperlandcontext.SaveChanges();


                var zipcode = _helperlandcontext.Users.Where(x => x.UserId == spid).ToList().FirstOrDefault().ZipCode;
                var zipcode_sps = _helperlandcontext.Users.Where(x => x.ZipCode == zipcode).ToList();
                var email_sp = _helperlandcontext.Users.Where(x => x.UserId == spid).ToList().FirstOrDefault().Email;
                foreach (var temp in zipcode_sps)
                {
                    var emailId = _helperlandcontext.Users.Where(x => x.UserId == temp.UserId).ToList().FirstOrDefault().Email;
                    if (emailId != email_sp)
                    {
                        MailMessage mm = new MailMessage("pmmakadiya1@gmail.com", emailId);
                        mm.Subject = "New Service Request Accepted";
                        mm.Body = "Service Request with ID " + sid + " is no more Available, It is Accepted By One of the service Provider";
                        mm.IsBodyHtml = false;
                        SmtpClient smtp = new SmtpClient();
                        smtp.Host = "smtp.gmail.com";
                        smtp.Port = 587;
                        smtp.EnableSsl = true;
                        NetworkCredential nc = new NetworkCredential("pmmakadiya1@gmail.com", "123456789@gmail.com");
                        smtp.UseDefaultCredentials = true;
                        smtp.Credentials = nc;
                        smtp.Send(mm);
                    }
                }
            }

            try
            {
                return Json(obj);
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }

        public IActionResult Upcoming_Services()
        {
            _helperlandcontext = new HelperlandContext();
            var username = HttpContext.Session.GetString("user");
            _helperlandcontext = new HelperlandContext();
            var userid = (_helperlandcontext.Users.Where(x => x.FirstName == username).ToList()).FirstOrDefault().UserId;
            var model_to_pass = _helperlandcontext.ServiceRequests.Where(x => x.ServiceProviderId == userid && x.Status == 3).ToList();
            List<Models.Book_now_Table> item = new List<Models.Book_now_Table>();
            foreach (Models.ServiceRequest temp in model_to_pass)

Tatvasoft_Project/Views/Service_Provider/Block_Customer.cshtml
@model Book_now_Table;
<html>
<head>

</head>

<body>
    <div style="display: flex;flex-wrap: wrap;">

        @foreach (var temp in ViewBag.all_cus)
        {
        <div style="margin-left: 15px; margin-top: 15px; text-align: center; min-height: 200px; width: 210px; border: 1px solid black;">
            <div style="margin-top: 20px;"><img src="~/images/cus_hat.png" style="height: 60px;width: 70px;border: 1px solid black;padding: 10px;border-radius: 50%;"></div>
            <div style="margin-top: 15px;">@temp.SP_Name</div>
          
                <button class="@temp.SP_ID" id="btn_blc" onclick="btn_val(@temp.SP_ID)" style="margin-top: 20px; background-color: #ff6b6b;color: white;
      border:none;border-radius: 15px;padding-top: 4px;padding-bottom: 4px;padding-left: 6px;padding-right: 6px;" type="button">
                @if(temp.Is_Blocked == 0)
                {
                    <span>Block</span>
                }
                else
                {
                    <span>UnBlock</span>
                }
                </button>
            
          

        </div>
        }


    </div>
   
    <script>
        var i = 0;
        function btn_val(idd) {
            if (document.getElementsByClassName(idd)[0].innerText == "Block") {
                document.getElementsByClassName(idd)[0].innerText = "UnBlock";
            }
            else {
                document.getElementsByClassName(idd)[0].innerText = "Block";
            }
            var obj = {
                "UserId": idd,
                "TargetUserId": parseInt(@ViewBag.uid)

            };
            $.ajax({
                type: "GET",
                url: "/Service_Provider/Check_Block_Customer",
                data: obj,
                contentType: "application/json; charset=utf-8",
                dataType: "json",
                success: function (data) {
                    
                },
                failure: function (response) {
                    alert(response.responseText);
                },
                error: function (response) {
                    alert(response.responseText);
                }
            });
        }
    </script>
</body>
</html>

Tatvasoft_Project/Views/Service_Provider/Ratings.cshtml
@model Book_now_Table;
<!DOCTYPE html>
<html>
<head>

    <style>
        .ncc {
            display: none;
        }
    </style>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Data Tables</title>

    <style>
        li {
            color: rgba(0,0,0,0.2);
        }
    </style>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>

    <script src="http://code.jquery.com/jquery-3.3.1.min.js"
            integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
            crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.19/css/jquery.dataTables.min.css">
    <script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>



    <link rel="stylesheet" type="text/css" href="style2.css">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
</head>
<body>


    <div class="container-fluid">
        <table class="table table-fluid" id="myTable10" style="color: #646464;">
            <thead>
                <tr>
                    <th></th>

                </tr>
            </thead>
            <tbody>
                @foreach (var temp in ViewBag.data)
                {
                    <tr >
                        <td style="border:1px solid black;padding-top:10px;padding-bottom:10px;">
                            <div class="row">
                                <div class="col-3">
                                    <div>@temp.ID</div>
                                    <div style="font-weight: bold;font-size: 17px;">@temp.SP_Name</div>
                                </div>
                                <div class="col-4">
                                    <div style="font-weight: bold;font-size: 17px;">
                                        <img src="~/images/us_cal.png" style="height: 17px;width: 17px;"> @temp.Booking_date.ToShortDateString()
                                    </div>
                                    <div>
                                        <img src="~/images/us_clock.png" style="height: 17px;width: 17px;"> @temp.Booking_duration
                                    </div>
                                </div>
                                <div class="col-5" style="text-align: right;">
                                    <div style="font-weight: bold;font-size: 17px;">Ratings</div>
                                    <div style="text-align: right;">

                                        @if (temp.SP_Ratings >= 0.5 && temp.SP_Ratings <= 1.5)
                                        {
                                            <img style="height: 16px;width: 17px;" src="~/images/cus_yellow_star.png">
                                            <img style="height: 16px;width: 17px;" src="~/images/cus_star.png">
                                            <img style="height: 16px;width: 17px;" src="~/images/cus_star.png">
                                            <img style="height: 16px;width: 17px;" src="~/images/cus_star.png">
                                            <img style="height: 16px;width: 17px;" src="~/images/cus_star.png">
                                            <span> Bad</span>
                                        }
                                        else if (temp.SP_Ratings >= 1.5 && temp.SP_Ratings <= 2.5)
                                        {
                                            <img style="height: 16px;width: 17px;" src="~/images/cus_yellow_star.png">
                                            <img style="height: 16px;width: 17px;" src="~/images/cus_yellow_star.png">
                                            <img style="height: 16px;width: 17px;" src="~/images/cus_star.png">
                                            <img style="height: 16px;width: 17px;" src="~/images/cus_star.png">
                                            <img style="height: 16px;width: 17px;" src="~/images/cus_star.png">
                                            <span> Not Bad</span>
                                        }
                                        else if (temp.SP_Ratings >= 2.5 && temp.SP_Ratings <= 3.5)
                                        {
                                            <img style="height: 16px;width: 17px;" src="~/images/cus_yellow_star.png">
                                            <img style="height: 16px;width: 17px;" src="~/images/cus_yellow_star.png">
                                            <img style="height: 16px;width: 17px;" src="~/images/cus_yellow_star.png">
                                            <img style="height: 16px;width: 17px;" src="~/images/cus_star.png">
                                            <img style="height: 16px;width: 17px;" src="~/images/cus_star.png">
                                            <span> Good</span>
                                        }
                                        else if (temp.SP_Ratings >= 3.5 && temp.SP_Ratings <= 4.5)
                                        {
                                            <img style="height: 16px;width: 17px;" src="~/images/cus_yellow_star.png">
                                            <img style="height: 16px;width: 17px;" src="~/images/cus_yellow_star.png">
                                            <img style="height: 16px;width: 17px;" src="~/images/cus_yellow_star.png">
                                            <img style="height: 16px;width: 17px;" src="~/images/cus_yellow_star.png">
                                            <img style="height: 16px;width: 17px;" src="~/images/cus_star.png">
                                            <span> Very Good</span>
                                        }
                                        else
                                        {
                                            <img style="height: 16px;width: 17px;" src="~/images/cus_yellow_star.png">
                                            <img style="height: 16px;width: 17px;" src="~/images/cus_yellow_star.png">
                                            <img style="height: 16px;width: 17px;" src="~/images/cus_yellow_star.png">
                                            <img style="height: 16px;width: 17px;" src="~/images/cus_yellow_star.png">
                                            <img style="height: 16px;width: 17px;" src="~/images/cus_yellow_star.png">
                                            <span> Excellent</span>
                                        }

                                    </div>
                                </div>
                            </div>
                            <hr style="color: black;">
                            <div style="font-weight: bold;font-size: 17px;">Customer Comment</div>
                            <div>@temp.Suggestion</div>
                        </td>

                    </tr>
                }
            </tbody>
        </table>
    </div>



    <script>
        $(document).ready(function () {
            $('#myTable10').DataTable();


        });
    </script>
</body>
</html>

Tatvasoft_Project/Views/Service_Provider/Upcoming_Services.cshtml
@model Book_now_Table;
<html>
<head>

    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js"></script>
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.20/css/jquery.dataTables.min.css">
    <link rel="stylesheet" type="text/css" href="https://datatables.net/media/css/site-examples.css">

    <!-- buttons -->
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/buttons/1.6.1/css/buttons.dataTables.min.css">
    <script src="https://code.jquery.com/jquery-3.3.1.js"></script>
    <script src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.6.1/js/dataTables.buttons.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.6.1/js/buttons.flash.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/pdfmake.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/vfs_fonts.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.6.1/js/buttons.html5.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.6.1/js/buttons.print.min.js"></script>
</head>
<body>

    <div class="modal fade" id="exampleModal_cancel_sp1" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true" style="background-color: gray;color: #646464;">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" style="font-size: 22px;font-weight: bold;" id="exampleModalCenterTitle">Cancel Service Request</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">



                    <form asp-action="Cancel_sr" asp-controller="Customer" method="post">
                        <label style="font-size: 17px;">Why you want to cancel the service request?</label>
                        <input asp-for="ID" type="hidden" id="id_cancel2" />
                        <input type="text" name="" style="width: 100%;height: 100px;">
                        <button type="submit" class="btn btn-primary"
                                style="width: 100%;border-radius: 30px;margin-top: 10px;font-size: 17px;" name="">
                            Cancel Now
                        </button>
                    </form>
                </div>

            </div>
        </div>
    </div>

    <div class="modal fade" id="exampleModal_complete_sp1" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true" style="background-color: gray;color: #646464;">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" style="font-size: 22px;font-weight: bold;" id="exampleModalCenterTitle">Cancel Service Request</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">



                    <form asp-action="Complete_srr" asp-controller="Service_Provider" method="post" style="text-align:center;">
                       <label>Have you Completed this Service?</label>
                        <input style="display:none;" type="text" asp-for="ID" id="id_f_cs"/>
                        <button type="submit" class="btn btn-success">Yes</button>
                        <button type="button" class="btn btn-danger" style="margin-left:10px;" data-toggle="modal" data-target="#exampleModal_complete_sp1">No</button>
                    </form>
                </div>

            </div>
        </div>
    </div>


    <table class="table table-fluid" id="myTable4" style="color: rgba(0,0,0,0.7);">
        <thead>
            <tr>
                <th>ID</th>
                <th>Service Details</th>
                <th>customer Details</th>
                <th>Payment</th>
                <th>Distance</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var temp in ViewBag.data)
            {


                <tr id="@temp.ID">
                    <td style="border-bottom:1px solid black;border-left:1px solid black;"><div style="margin-top: 15px;font-size: 18px;"><span class="@temp.ID">@temp.ID</span></div></td>
                    <td style="border-bottom: 1px solid black;" onclick="demoo3(@temp.ID,5)" data-toggle="modal" data-target="#exampleModal2">
                        <div class="us_d1">
                            <div style="font-weight: bold;"><img style="height: 16px;width: 17px;" src="~/images/cus_cal.png"> <span class="@temp.ID">@temp.Booking_date.ToShortDateString()</span></div>
                            <div class="@temp.ID">@temp.Booking_duration</div>
                        </div>
                    </td>
                    <td style="border-bottom: 1px solid black;">
                        @if (temp.SP_ID != 0)
                        {
                            <div style="display:flex;">
                                <div>
                                    <button style="border:none;"><img style="height:20px;width:20px;border:none;padding:0px;" src="~/images/us_home.png"></button>
                                </div>
                                <div class="cus_ht_txt">
                                    <div class="cus_ht_txt1 @temp.ID">@temp.SP_Name</div>
                                    <div><span class="@temp.ID">@temp.Street</span> <span class="@temp.ID">@temp.House_number</span></div>
                                    <div><span class="@temp.ID">@temp.Zipcode</span>, <span class="@temp.ID">@temp.Location</span></div>
                                </div>
                            </div>
                        }
                        else
                        {

                        }
                    </td>
                    <td style="border-bottom: 1px solid black;">
                        <div style="font-size: 24px;
  font-weight: bold;
  color: #1d7a8c;margin-top: 10px;" class="cus_pay @temp.ID">
                            €@temp.Discounted_cost
                        </div>
                    </td>
                    <td style="border-bottom: 1px solid black;">
                        &nbsp;
                    </td>
                    <td style="border-bottom: 1px solid black;border-right:1px solid black;">
                        @if (temp.Is_Date_Smaller == 0)
                        {
                            <button onclick="demo_set_ic(@temp.ID)" data-toggle="modal" data-target="#exampleModal_cancel_sp1"
                                    style="background-color: #ff6b6b; border-radius:5px;border:none; margin-top:20px;
                        color:white;">
                                Cancel
                            </button>
                        }
                        else
                        {
                            <button onclick="demo_set_if_complete(@temp.ID)" data-toggle="modal" data-target="#exampleModal_complete_sp1"
                                    style="background-color: rgba(0,200,0,0.8); border-radius:5px;border:none; margin-top:20px;
                        color:white;">
                                Complete
                            </button>
                        }
                    </td>

                    <div class="@temp.ID" style="display:none;">@temp.Suggestion</div>
                    <div class="@temp.ID" style="display:none;">@temp.Booking_time</div>
                    <div class="@temp.ID" style="display:none;">@temp.Phone</div>
                </tr>


            }
        </tbody>
    </table>
    <script>
        function demo_set_ic(id2) {
            document.getElementById("id_cancel2").value = id2;
        }

        function demo_set_if_complete(id4) {
            document.getElementById("id_f_cs").value = id4;
        }
    </script>
    <script>
        $('#myTable4').DataTable();

        $('#myTable4').parents('div.dataTables_wrapper').first().show();
    </script>
</body>
</html>